install_data(
  application_id + '.desktop',
  install_dir: datadir / 'applications',
)

install_data(
  application_id + '.metainfo.xml',
  install_dir: datadir / 'metainfo',
)

install_data(
  'icons/hicolor/scalable/apps' / application_id + '.svg',
  install_dir: datadir / 'icons' / 'hicolor' / 'scalable' / 'apps',
)
